name = "PrintTypeTree"
uuid = "03751d76-14c6-4844-8d34-798a6a45b277"
authors = ["Junfeng Qiao <qiaojunfeng@outlook.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
