name = "PrintTypeTree"
uuid = "03751d76-14c6-4844-8d34-798a6a45b277"
authors = ["Junfeng Qiao <qiaojunfeng@outlook.com> and contributors"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
AbstractTrees = "0.4.5"
InteractiveUtils = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
